METHODS = ('DP-KFC', 'DP-KFLR', 'DP-KFRA-block')
SEEDS = (42, 7)
EPOCHS = 5
BATCH_SIZE = 256
LEARNING_RATE = .5
MOMENTUM = WEIGHT_DECAY = 0
EPSILON = 1.
DELTA = 1e-5
MAX_GRAD_NORM = 1.
DAMPING = 1e-3
SYNTHETIC_BATCHES = 10
SYNTHETIC_BATCH_SIZE = 256
