"""Exp14b protocol, with a denser exponent sweep."""
from exp14b.config import (SEEDS, EPOCHS, BATCH_SIZE, LEARNING_RATE, MOMENTUM,
    WEIGHT_DECAY, EPSILON, DELTA, MAX_GRAD_NORM, DAMPING,
    SYNTHETIC_BATCHES, SYNTHETIC_BATCH_SIZE)
BETAS = (0., .125, .25, .375, .5, .75, 1.)
SMOKE_BETAS = (0., .25, .5)
PROBE_SAMPLES = 256
PROBE_BATCH_SIZE = 8
PRIVATE_STEPS = EPOCHS * (60000 // BATCH_SIZE)
